### ISSUE TITLE
네트워크 불안정에 대한 피드백 제안

### ISSUE THREAD

**Issue by jinwoong16** [hellotunamayo/PokedexProject#26]
## Issue
지금의 EntryView는 네트워크가 불안정하여 데이터를 받아오는 시간이 오래걸릴 때, 그에 대한 피드백을 주지 못하고 있습니다. 단순히 비어있는 화면을 보여줄 뿐이죠. 이 부분에 피드백이 필요한 것으로 보입니다.

<div align="center"> 
<img src="https://github.com/hellotunamayo/PokedexProject/assets/26710036/db1fb8ed-0be1-4668-a5d5-a5ce74cc8c95" width="200" />
</div>

## Proposed Feature
네트워킹이 끝날 때까지, 해당 화면에 Progress View를 삽입해두면 좋을 것 같습니다. 적어도 현재 진행상황에 대한 피드백은 충분히 될 것이라 생각합니다.

**Comment by hellotunamayo** [comment]
엑스코드에서 네트워크 상태 구리게 시뮬레이션 하는법좀...

**Comment by jinwoong16** [comment]
> 엑스코드에서 네트워크 상태 구리게 시뮬레이션 하는법좀...

[여기](https://medium.com/macoclock/how-to-simulate-poor-network-conditions-on-ios-simulator-and-iphone-faf35f0da1b5)링크의 방법으로 맥에서 시뮬레이터로 배드 네트워크 테스트 가능해요. 

혹은 실물기기에서 설정-개발자 에 있는 네트워크 설정으로도 가능해요. 
![IMG_1956](https://github.com/hellotunamayo/PokedexProject/assets/26710036/7fe528c5-da9b-4b10-b0c8-801a2cad71c4)

이 이슈랑 관련한거랑 다른거랑 같이 개선해봤는데 PR올릴 시간이 없어서… 오늘내로 올려보겠읍니다!
